language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: LmsBQKJ+IqqMQCI5+P9+8XzC+IKSYp1lKxfvFQDZbHUytDoq+PAdPhhAEnEA8BfdBcmta1NQBSqdlQdewfEYXRnn8ykyqWxY4rfCFKnTuGLU8YeUt82ChF9f46Q8YOjFw2vc0WLXQTbMePwwYYUVEWzoySWmwhvb4hYDLgwMAtTESvmr2iVPtgKrE7lfRSdZreQCWyit58JCdUC3J9bhgMI5mX7SFNr64cur8xFOh0tqEk5bBUr77gObGfdTAY4IyWSOLGU6VbNARXY1b6AAl4KGy9isJ/6qbPYY7KO2IVodZybfzR+s0PPpjzrt4rZxEcmMH8+wJAqP0p+vLzZSMxuHrgHjfdxRWP7l3R6zofRILiaKLHLhUv1IYpk6kRRV7J+GLpj5uFF6aSegtrTSAHil43FNytNskBhcFl8INvrrHPMDljDnEahcJIMbPJmXpITfVaAGxkpuuB3hQOjzS4GAfElVMLsKPrFWDc/97HYXiKYxUeTV4LsRU6gi1UWCmh+UblgpvtXK8lCQq9zgW0QIT9mRf++5zy3JpYDHlsFj0UUlbrz1njbyTLEjQSpGorr+AaoLP6Ka1B3WsY3UvLUQzrOeRWJhgdcjT0g2ksPpHg0NXZmJ4bpNR/IZ1chaULi8CmjHDYcO4DiuE2sZmGW/CAUNC2CFGjsUgbc3ZEc=
  run: rake db:migrate
  app: protected-dawn-36398
  on:
    repo: jiial/Web-palvelinohjelmointi-syksy-2018
env:
  matrix:
    secure: hih4u6/CTHQKma0s8wEqWUtzNG2m6QPEThm4ooNx8yDXpMOzf9yiyOvx/MJ0dMlsBI0lcX8gkYk8+NneSrHRRcjYgZuk6AG3pSQA7qALvGeAjMZz/SXes10JUpEQDa6f8Q6JYxWpUdrRBp2kXrpmP9NJM6cQ71BgIk3JGp24B0A6MD+C/FbG4q4N94GyRWcIBrbXZPhRrx2bWn38/cuS3akV/BdfDt+qPwhVlA8RLuIuWhPdXQs864NNIIIwgmAsCxb/KId40WlUhIbd0jVe2u2E55YU2KmQtm6LA46iUByfwu8UC0WIpWw0DVOXt4ZvN2ZOzd6eWMZNjxCDNYukT/Xad1QJS2YM+bgaimS75Nkk9x41OxgFud0TlNU/t7157xR22YzZQ8R0hzdmtaKJz84fJxFGnf1dL651nwkmTWtWPeNyhG8edba+E7w1iintObNbMMIUjv+F0amk88F4bERQ1/Ec61NxUJGwmy+zJ0SeFeCrc6NWP2PuyqhbNmeoLuiONGc891nvy92D7frdO4TVMVYIcnirUO9BEYUcY7SbA+p4HSULTYalzMcf6l6RFaKc8+SCwl2AP3MeHHFdq8J7Y/+1XkLA2cEckTl8XYkoVHLkDLQXpnSVku4W4W24To6bKPdjtTX3yVWR2jJZ3KpYzHX6tUm9s2vTzpvVLf4=
